name: noelc
favicon: null
layout_spectrum: 0.47426825668662786
typography_spectrum: 0.29517672676593065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7008410629350692
  lightness: 0.4618499455973506
  saturation: 0.35695990128442645
  rhythmicContrast: 0.6551567791029811
purpose: []
